### ISSUE TITLE
Mapping CollRef

### ISSUE THREAD

**Issue by renannery** [kdy1/typed_firestore#1]
How can I extrat a plain object from your example?
Let's say I need to get the first **car**.

final CollRef<Car> cars = firestore.collection<Car>('cars');
final Car car = cars.???

**Comment by wstrange** [comment]
@renannery I don't think this is possible. You get a map back (same as the other firestore libraries). You need to write code to serialize / de-serialize the json map to and from Dart objects.

**Comment by kdy1** [comment]
```dart
final CollRef cars = firestore.collection('cars');
final Car car = (await cars.get()).docs.first.data;
```

Note that you need to register Car's serializer using `@SerializerFor`.
